### PR TITLE
Update memmap2 to 0.9.3

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by glandium** [comment]
I guess this needs a version bump...

**Comment by gabrielesvelto** [comment]
> I guess this needs a version bump...

There a few fixes that have landed in the past months, I can cut a new release.

**Comment by glandium** [comment]
To be clear, I meant a semver bump.

I'm thinking Mmap should probably be re-exported from minidump, or Minidump<'a, Mmap> aliased so that dependencies of the crate don't need to have a dependency on memmap2 to use it.

**Comment by gabrielesvelto** [comment]
OK, I can do a major version bump after we're done with the changes (there's more fixes in the pipeline for Socorro so this week is a good time).

**Pull request merged**
