### PR TITLE
Split stackwalking out of the minidump-processor crate.

### LINKED ISSUE #816: Split the stack walking behavior out of `minidump-processor`
The new `minidump-analyzer` binary relies on `minidump-processor` for stack walking. However, this brings along a lot of extra dependencies which are unused (e.g. `yaxpeax`). Normally this might be a situation where a feature would be appropriate, however in combination with a need to audit dependencies with `cargo-vet`, it would make things much simpler to have stack walking as a separate crate.

Besides stack walking functionality, `minidump-analyzer` also needs the new debug info symbol provider from `minidump-processor`. That will need to go into a potentially new split-out crate, or there could be _another_ crate with symbol providers. It is annoying that `cargo-vet` can't support features so it forces us to break functionality into little pieces, though ultimately there isn't that much overhead aside from e.g. coordinating future additions that need to change multiple crates. The vendoring/auditing team felt much more comfortable with splitting the crates up (if possible) rather than adding a bunch of exemptions for the enormous crates which we aren't actually using. Not to mention vendoring those large crates would be cumbersome, too (or at the very least hacky with some dummy/stubbed out/patched versions).

@Gankra I'm wondering if you have any thoughts on this?

### PR DESCRIPTION
**Pull request by afranchuk**
The new minidump-walk-stack crate handles it and has far fewer dependencies.

Closes #816.

Notes:
* `minidump-walk-stack` isn't a great name. Pending a decision in #824 it may be changed to be clearer.
* Do we want to re-export `minidump-walk-stack` in `minidump-processor` so that the latter keeps the same API as before (and as a convenience to users)?

### CODE REVIEW

**Review by gabrielesvelto — APPROVED** [review]
This is fine I've just been wondering a bit about the naming especially WRT to https://github.com/rust-minidump/rust-minidump/issues/824. Renaming a crate is not a big deal, we could easily move `minidump-stackwalk` to `minidump-analyzer` and put a forwarding crate in its place to guarantee that the new crate is picked up. However using the old name of a crate for a new one - such as this one - is problematic as AFAIK cargo wouldn't be able to support it.

So here's my proposal, why don't we call the new crate `minidump-unwind` to clearly distinguish it from `minidump-stackwalk`? We can always rename `minidump-stackwalk` to `minidump-analyzer` later to make the distinction clearer.

Aside from this the PR is fine.

**Comment by afranchuk** [comment]
Okay, I've renamed the crate to `minidump-unwind`.

**Comment by afranchuk** [comment]
I don't know why CI is failing (invalid cache?).

**Comment by gabrielesvelto** [comment]
> I don't know why CI is failing (invalid cache?).

The folder is still called `minidump-walk-stack`, it's looking for `minidump-unwind` instead.

**Comment by afranchuk** [comment]
> > I don't know why CI is failing (invalid cache?).
> 
> The folder is still called `minidump-walk-stack`, it's looking for `minidump-unwind` instead.

:facepalm: didn't add the _new_ folder (it just removed the old one). Probably should use `git mv` more often.

**Comment by gabrielesvelto** [comment]
Merging. Once we're done with the work here I'll make a major version release since we're adding an entirely new crate.

**Pull request merged**
